name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile en
      run: cd /makefile/en/ && make

    - name: Compile fr
      run: cd /makefile/fr/ && make


    - uses: actions/upload-artifact@v4
      with:
        name: cv
        path: cv/*.pdf
